import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
const url = "http://localhost:8000/blogs";

export default function Home() {
  const router = useRouter();
  const [data, setData] = useState([])
  async function getData() {
    const res = await fetch(url);
    const data = await res.json();
    setData(data)
  }
  useEffect(() => {
    getData()
  }, [])

  
  interface obj{
    title:"string",
    blogtext:"string",
    id:"string"
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Welcome to blog page</h1>
        <Link href="/addpost">Add New Blog</Link>
        <div className={styles.blog}>
          <div className={styles.blogtext}>
            {data.map((blog:obj)=>{
              return(
                <div key={blog.id}>
                  <h3><Link href={{
                    pathname: '/post',
                    query: {title : blog.title, blogText: blog.blogtext, id:blog.id},
                  }}
                  as= {`/post/${blog.title}`}
                  >{blog.title}</Link></h3>
                 
                 
                </div>
              )
            })}
          </div>

        </div>
      </main>
    </>
  );
}

